# Numpy

In [1]:
import numpy as np

Q 一次元の配列を作成する  
サイズを確認する  
次元数を確認する  
要素を指定して、値を確認する  


In [2]:
x = np.array([1, 2, 3])
print(x)
print(x.shape)
print(x.ndim)
print(x[0])

[1 2 3]
(3,)
1
1


Q 2次元の配列を作成する  
サイズを確認する  
次元数を確認する  
要素を指定して、値を確認する  

In [3]:
x = np.array([[1, 2, 3], [0, 1, 1]])
print(x)
print(x.shape)
print(x.ndim)
print(x[1][2])

[[1 2 3]
 [0 1 1]]
(2, 3)
2
1


Q (1,3)のサイズの配列を作成する

In [4]:
x = np.array([[1, 2, 3]])
print(x.shape)

(1, 3)


Q サイズ1x2の0配列を作成  
2x2の0配列を作成する  
x = np.array([[1, 2], [3, 4], [5, 6])と同じサイズの0配列を作成する  

In [5]:
x = np.zeros((2))
y = np.zeros((2,2))

t = np.array([[1, 2], [3, 4], [5, 6]])
z = np.zeros_like(t)

print(x)
print(x.shape)

print(y)
print(y.shape)

print(z)
print(z.shape)


[0. 0.]
(2,)
[[0. 0.]
 [0. 0.]]
(2, 2)
[[0 0]
 [0 0]
 [0 0]]
(3, 2)


Q サイズ1x2の1配列を作成  
2x2の1配列を作成する  
x = np.array([[1, 2], [3, 4], [5, 6])と同じサイズの1配列を作成する  

In [6]:
x = np.ones((2))
y = np.ones((2,2))

t = np.array([[1, 2], [3, 4], [5, 6]])
z = np.ones_like(t)

print(x)
print(x.shape)

print(y)
print(y.shape)

print(z)
print(z.shape)


[1. 1.]
(2,)
[[1. 1.]
 [1. 1.]]
(2, 2)
[[1 1]
 [1 1]
 [1 1]]
(3, 2)


Q 単位行列を作成する

In [7]:
i = np.eye(4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Q 配列の要素の平均、分散、標準偏差、最大、最小を確認する  
t = np.array([[1, 2], [3, 4], [5, 6]])

In [8]:
t = np.array([[1, 2], [3, 4], [5, 6]])
print(t.mean())
print(t.var())
print(t.std())
print(t.max())
print(t.min())

3.5
2.9166666666666665
1.707825127659933
6
1


Q 配列のデータ型の確認方法  
データ型を指定して配列を生成する  
データ型を変更する  

In [9]:
t = np.array([[1, 2], [3, 4], [5, 6]])
print(t.dtype)

t = np.array([[1, 2], [3, 4], [5, 6]], dtype='float32')
print(t.dtype)

t = np.array([[1, 2], [3, 4], [5, 6]])
t = t.astype(np.float32)
print(t.dtype)


int32
float32
float32


Q 行列積  
a = np.array([[1, 0], [0, 1]])  
b = np.array([[2, 0], [3, 1]])  

In [10]:
a = np.array([[1, 0], [0, 1]])
b = np.array([[2, 0], [3, 1]])

c = a @ b
d = a.dot(b)
print(c)
print(d)

[[2 0]
 [3 1]]
[[2 0]
 [3 1]]


Q 対象の行列に対して、以下の操作をする  
3以上なら、True, それ以外はFalseとなる行列を生成する  


In [11]:
t = np.array([[1, 2], [3, 4], [5, 6]])
t = (t >= 3)
t

array([[False, False],
       [ True,  True],
       [ True,  True]])

Q 配列：要素の選択  
0,1の要素を指定する　2パターン  
0~1, 1~2の部分行列を抜き出す  


In [12]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x[0][1])
print(x[0, 1])

print(x[0:2, 1:3])
print(x[0:2][1:3])  # 同じ動きではない


2
2
[[2 3]
 [5 6]]
[[4 5 6]]


Q 数列生成：0~1を15等分した数列を生成する

In [13]:
x = np.linspace(0, 1, 15)
x

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

Q 数列生成：-3~3を幅0.3で分割した数列を生成する

In [14]:
x = np.arange(-3, 3, 0.3)
x

array([-3.00000000e+00, -2.70000000e+00, -2.40000000e+00, -2.10000000e+00,
       -1.80000000e+00, -1.50000000e+00, -1.20000000e+00, -9.00000000e-01,
       -6.00000000e-01, -3.00000000e-01, -1.77635684e-15,  3.00000000e-01,
        6.00000000e-01,  9.00000000e-01,  1.20000000e+00,  1.50000000e+00,
        1.80000000e+00,  2.10000000e+00,  2.40000000e+00,  2.70000000e+00])

Q 乱数：  
指定した範囲の乱数(float)を取得  
指定した範囲の乱数(int)を取得  


In [15]:
rf = np.random.uniform(2, 4)
print(rf)
ri = np.random.randint(2,4)
print(ri)



2.014062680222537
3


Q サイズを指定して、0~1の間の配列を生成する。

In [16]:
x = np.random.random((3,2))
x

array([[0.3883981 , 0.09450127],
       [0.72800729, 0.94483141],
       [0.78867599, 0.95896404]])

Q 配列の中身をランダムに取得  
l = ["apple", "banana", "melon", "strawberry", "peach", "lemon"]

In [17]:
l = ["apple", "banana", "melon", "strawberry", "peach", "lemon"]
print(np.random.choice(l))

banana


Q 配列の中身をシャッフルする  
l = ["apple", "banana", "melon", "strawberry", "peach", "lemon"]

In [18]:
l = ["apple", "banana", "melon", "strawberry", "peach", "lemon"]
np.random.shuffle(l)
print(l)

['lemon', 'melon', 'banana', 'strawberry', 'peach', 'apple']


Q 配列の要素を様々な方向で合算する。
縦方向、横方向、などなど

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])
# すべての和
print(a.sum())
# 列ごとの和
print(a.sum(axis=0))
# 行ごとの和
print(a.sum(axis=1))
# 0列目の和
print(a[:, 0].sum())
# 1列目の和
print(a[:, 1].sum())


21
[ 9 12]
[ 3  7 11]
9
12


参考URL：  
<https://qiita.com/ProfessorQX/items/08ed3cb40bce58fbae8e#%E8%A1%8C%E5%88%97%E6%AC%A1%E5%85%83%E6%95%B0%E3%82%92%E7%A2%BA%E8%AA%8D>  
<https://www.sejuku.net/blog/20915>  